# Generated by Django 5.0 on 2023-12-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='image',
        ),
        migrations.AddField(
            model_name='proyect',
            name='media',
            field=models.FileField(default='default_value.mp4', upload_to='Proyects'),
        ),
    ]
